/**
  ******************************************************************************
  * @file    wcl.c
  * @brief   Wireless Communication Layer - BAU (STM32) side. See wcl.h.
  ******************************************************************************
  */
#include "wcl.h"

#include "main.h"          /* HAL, GPIO/UART types */
#include "cobs.h"
#include "alive.pb.h"      /* generated by nanopb from proto/alive.proto */
#include "pb_encode.h"

#include <string.h>

/* ---- Configuration -------------------------------------------------------- */
#define WCL_UART_BAUD   921600u   /* matches design doc section 3.2.4 */

/* USART1 handle, owned entirely by this module. */
static UART_HandleTypeDef hwcl_uart;

/* Monotonic frame counter. */
static uint32_t wcl_seq;

/* Scratch buffers. alive_BiometricFrame_size is the nanopb-computed worst-case
 * encoded length; the COBS buffer adds framing overhead plus the 0x00 delimiter. */
static uint8_t pb_buf[alive_BiometricFrame_size];
static uint8_t frame_buf[cobs_encode_bufsize(alive_BiometricFrame_size) + 1u];

/* ---- USART1 low-level init ------------------------------------------------ */
/* USART1 lives on APB2; TX=PA9, RX=PA10 (AF7). We do this by hand rather than
 * via CubeMX so regenerating the .ioc will not clobber the WCL bridge. */
static bool wcl_uart_init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_USART1_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};
    gpio.Pin       = GPIO_PIN_9 | GPIO_PIN_10;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_PULLUP;
    gpio.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
    gpio.Alternate = GPIO_AF7_USART1;
    HAL_GPIO_Init(GPIOA, &gpio);

    hwcl_uart.Instance          = USART1;
    hwcl_uart.Init.BaudRate     = WCL_UART_BAUD;
    hwcl_uart.Init.WordLength   = UART_WORDLENGTH_8B;
    hwcl_uart.Init.StopBits     = UART_STOPBITS_1;
    hwcl_uart.Init.Parity       = UART_PARITY_NONE;
    hwcl_uart.Init.Mode         = UART_MODE_TX_RX;
    hwcl_uart.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    hwcl_uart.Init.OverSampling = UART_OVERSAMPLING_16;

    return (HAL_UART_Init(&hwcl_uart) == HAL_OK);
}

bool WCL_Init(void)
{
    wcl_seq = 0;
    return wcl_uart_init();
}

bool WCL_SendBiometricFrame(float roll, float pitch, float yaw, bool imu_valid,
                            float hr_bpm, bool hr_valid,
                            float gsr, bool gsr_valid)
{
    alive_BiometricFrame frame = alive_BiometricFrame_init_zero;

    frame.seq          = wcl_seq++;
    frame.timestamp_ms = HAL_GetTick();
    frame.imu_roll     = roll;
    frame.imu_pitch    = pitch;
    frame.imu_yaw      = yaw;
    frame.imu_valid    = imu_valid;
    frame.hr_bpm       = hr_bpm;
    frame.hr_valid     = hr_valid;
    frame.gsr_conductance = gsr;
    frame.gsr_valid    = gsr_valid;

    /* 1. Protobuf encode. */
    pb_ostream_t os = pb_ostream_from_buffer(pb_buf, sizeof(pb_buf));
    if (!pb_encode(&os, alive_BiometricFrame_fields, &frame)) {
        return false;
    }

    /* 2. COBS frame + 0x00 delimiter. */
    size_t n = cobs_encode(pb_buf, os.bytes_written, frame_buf);
    frame_buf[n++] = 0x00;

    /* 3. Push to the ESP32. Blocking TX is fine at 921600 baud: ~35 bytes take
     *    ~0.4 ms, well inside the 10 ms motion-sample period. Swap to
     *    HAL_UART_Transmit_DMA once the scheduler is interrupt-driven. */
    return (HAL_UART_Transmit(&hwcl_uart, frame_buf, (uint16_t)n, 20) == HAL_OK);
}
